version: '3'
services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - '3000:3000'

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - '3001:3001'
    environment:
      DB_HOST: "db"
      DB_PORT: 5432
      DB_USER: "test"
      DB_PASSWORD: "test"
      DB_DATABASE: "test"
    depends_on:
      api-db-init:
        condition: service_completed_successfully

  api-db-init:
    build:
      context: ./api
      dockerfile: Dockerfile
    entrypoint: npm run db:migrate
    environment:
      DB_HOST: "db"
      DB_PORT: 5432
      DB_USER: "test"
      DB_PASSWORD: "test"
      DB_DATABASE: "test"

  db:
    image: "postgres:latest"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "test"
      POSTGRES_PASSWORD: "test"
      POSTGRES_DB: "test"
